//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLI_Tool {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CLI_Tool.Resources.DisplayResources", typeof(DisplayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        internal static string HelpHeading {
            get {
                return ResourceManager.GetString("HelpHeading", resourceCulture);
            }
        }
        
        internal static string HelpCopyright {
            get {
                return ResourceManager.GetString("HelpCopyright", resourceCulture);
            }
        }
        
        internal static string HelpUsage {
            get {
                return ResourceManager.GetString("HelpUsage", resourceCulture);
            }
        }
        
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        internal static string ErrorHint {
            get {
                return ResourceManager.GetString("ErrorHint", resourceCulture);
            }
        }
        
        internal static string DisplaySupportedAlgorithms {
            get {
                return ResourceManager.GetString("DisplaySupportedAlgorithms", resourceCulture);
            }
        }
        
        internal static string ErrorUnknownOption {
            get {
                return ResourceManager.GetString("ErrorUnknownOption", resourceCulture);
            }
        }
        
        internal static string ValidationSuccessMessage {
            get {
                return ResourceManager.GetString("ValidationSuccessMessage", resourceCulture);
            }
        }
        
        internal static string ValidationFailMessage {
            get {
                return ResourceManager.GetString("ValidationFailMessage", resourceCulture);
            }
        }
        
        internal static string FileChekcedMessage {
            get {
                return ResourceManager.GetString("FileChekcedMessage", resourceCulture);
            }
        }
        
        internal static string SelectedAlgorithmMessage {
            get {
                return ResourceManager.GetString("SelectedAlgorithmMessage", resourceCulture);
            }
        }
        
        internal static string ComputedChecksumMessage {
            get {
                return ResourceManager.GetString("ComputedChecksumMessage", resourceCulture);
            }
        }
        
        internal static string ProvidedChecksumMessage {
            get {
                return ResourceManager.GetString("ProvidedChecksumMessage", resourceCulture);
            }
        }
    }
}
